### ISSUE TITLE
Resident application error for admin, filtering issues and search malfunction

### ISSUE THREAD

**Issue by fwedwicc** [itgauy/bms-prod#44]
- Search functionality is malfunctioning due to being re-rendered every 10 seconds.
- Application status displays incorrectly due to an undefined value in the table, causing the filter to malfunction.
- The residency status fails to retrieve accurate data, displaying incorrect classifications instead of the expected 'Homeowner' or 'Renter/Tenant,' which results in filter malfunctions.

![image](https://github.com/user-attachments/assets/607eb503-0b22-4614-bf6b-c12a01a3bc58)

**Comment by itgauy** [comment]
Don't use reload time interval, instead I suggest using laravel echo and pusher js

> npm install --save laravel-echo pusher-js

Never tested it, so it depends on you. Or just remove the interval reload, but the user have to reload manually the page. (This is fine too temporarily)
